### ISSUE TITLE
Hide button disappears when I return to inbox from an email

### ISSUE THREAD

**Issue by nuaniall** [peterhartree/inbox-when-ready#7]
Hi,
When I click 'Show Inbox' and then go into an email, on my return the 'hide inbox' button has disappeared and I have to refresh again in order to start over. 

Cheers.

**Comment by peterhartree** [comment]
Hmm... sorry to hear you're having trouble. Are you seeing this issue when using regular Gmail or Inbox by Gmail?

**Comment by nuaniall** [comment]
Regular Gmail Peter.

**Comment by peterhartree** [comment]
OK thanks. I'd love to get this fixed for you ASAP.

I use this extension daily and I don't see the issue you describe. I've just tried using the extension on my test account with Chrome in Incognito, and again, I see the expected behaviour:

http://g.recordit.co/41WUZ64aad.gif

Two questions:

1. Can you describe what exact steps you take in order to see this issue? Are they the same as the ones I'm taking in the screencast above?

2. Can you try using the extension in Chrome in Incognito mode (with all other extensions disabled)? 

At the moment, my best guess is that there may be a conflict here between Inbox When Ready and some other Chrome extension you're using. It'd be particularly worth trying Inbox When Ready with any other Gmail specific Chrome extensions disabled.

**Comment by nuaniall** [comment]
Hi Peter and thanks for coming back to me. 

Murphy's law is playing it's part as it's back working again but I know for sure that the steps were exactly as you highlighted in your screencast.  If it happen again I'll run some tests and try identify any particular patterns or conflicts.

**Comment by peterhartree** [comment]
Great, thanks! 

If you see the issue again it'd be super helpful if you could:

1. Go to View > Developer > Javascript Console and paste the contents of the console window into this ticket.
2. Still in developer tools, click the "Elements" tab and then right click on the <html> element. Click "Edit as HTML" and then paste the highlighted text into this ticket.

**Comment by nuaniall** [comment]
I've no idea what that means but I'll certainly follow the instructions
when I encouter the error again!

I uninstalled "Pause Inbox" earlier so I'm wondering was there a conflict
there...
ᐧ


*Best Regards*



<https://www.google.ie/maps/place/Ireland's+Raw+Kitchen/@53.276635,-9.07718,17z/data=!3m1!4b1!4m2!3m1!1s0x485b965be8a31535:0x5e55145bdfa8895a?hl=en>

*......................................................................................
*
*NIALL FENNELL
 *
*Sales Manager*
*......................................................................................*
*M: *+353 (0)85 7587272     E:  niall@nuanaturals.com
<design@nuanaturals.com>
T:  +353 (0)91 518107       W: www.nuanaturals.com
*F:  *+353 (0)91 396392
*......................................................................................*
*NUA Naturals *Unit 8, Westside Enterprise Centre,
Galway, H91 YW53,  Ireland
*......................................................................................*
<https://www.facebook.com/nuanaturals>   <https://twitter.com/nuanaturals>
<http://instagram.com/nuanaturals>   <http://www.pinterest.com/NUANaturals/>
  facebook <https://www.facebook.com/nuanaturals> | twitter
<https://twitter.com/nuanaturals> | pinterest
<http://www.pinterest.com/NUANaturals/> | instagram
<http://instagram.com/nuanaturals>

<http://www.nuanaturals.com>

All information contained in this email is confidential to the recipient.
If you are not the intended recipient, kindly redirect this email and its
attachments to its source. Where appropriate, Ireland’s Raw Kitchen asserts
its ownership of, and copyright to, all images, sound, graphics and other
material attached to this email. Reproduction without the authors' express
permission is strictly prohibited. Foca Organics Limited T/A NUA Naturals
is registered in Ireland Cro No: 494325 VAT No: 9777935W.

**Comment by peterhartree** [comment]
I've not heard from you for awhile so I'll assume this issue is resolved. Please just get in touch again if you're still having trouble.

**Comment by nuaniall** [comment]
Hi Peter and thanks for getting in touch.

No problem with the multiple buttons appearing any more, which is great,
but I've just got used to pressing refresh when the button disappears.

It still happens when I go working within gmail and then press back or
inbox. It happens most of the time but no specific identifiable patter
emerging.

Sorry I can't be more specific!

It'd be great to have it resolved but it's not a deal breaker for me..





*Best Regards*



<https://www.google.ie/maps/place/Ireland's+Raw+Kitchen/@53.276635,-9.07718,17z/data=!3m1!4b1!4m2!3m1!1s0x485b965be8a31535:0x5e55145bdfa8895a?hl=en>

*......................................................................................
*
*NIALL FENNELL
 *
*Sales Manager*
*......................................................................................*
*M: *+353 (0)85 7587272     E:  niall@nuanaturals.com
<design@nuanaturals.com>
T:  +353 (0)91 518107       W: www.nuanaturals.com
*F:  *+353 (0)91 396392        L:  Linked i*n*
<https://www.linkedin.com/in/niall-fennell-b941aa36>
*......................................................................................*
*NUA Naturals *Unit 8, Westside Enterprise Centre,
Galway, H91 YW53,  Ireland
*......................................................................................*
<https://www.facebook.com/nuanaturals>   <https://twitter.com/nuanaturals>
<http://instagram.com/nuanaturals>   <http://www.pinterest.com/NUANaturals/>
  facebook <https://www.facebook.com/nuanaturals> | twitter
<https://twitter.com/nuanaturals> | pinterest
<http://www.pinterest.com/NUANaturals/> | instagram
<http://instagram.com/nuanaturals>

<http://www.nuanaturals.com>

All information contained in this email is confidential to the recipient.
If you are not the intended recipient, kindly redirect this email and its
attachments to its source. Where appropriate, Ireland’s Raw Kitchen asserts
its ownership of, and copyright to, all images, sound, graphics and other
material attached to this email. Reproduction without the authors' express
permission is strictly prohibited. Foca Organics Limited T/A NUA Naturals
is registered in Ireland Cro No: 494325 VAT No: 9777935W.

**Comment by peterhartree** [comment]
Thanks for the update. I'm sorry to hear you're still having trouble. I've re-opened this issue and I'll keep you posted with any updates. If you do notice a set of steps that leads to this issue reliably, please do let me know what they are.

**Comment by nuaniall** [comment]
Will do!

-Niall

**Comment by matadur** [comment]
+1 for issue; saw this happen once recently. I'll see if I can troubleshoot it if it happens again.
